# This is a basic workflow to help you get started with Actions

name: data.json update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # schedule:
  #   - cron: 0 */3 * * *

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout the main repo
    - name: Checkout Main repo
      uses: actions/checkout@v2
      with:
        path: site

    # Checkout data scraper repo
    - name: Checkout Data Scraper
      uses: actions/checkout@v2
      with:
        repository: sfbrigade/data-covid19-sfbayarea
        path: scraper

    # Install Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    
    # Install dependencies
    # - The commit that was checked out will be available as $SCRAPER_COMMIT.
    - name: Install Data Scraper & Dependencies
      run: |
        cd ${GITHUB_WORKSPACE}/scraper
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
        # Keep track of the version used so we can use it in commit messages
        echo "::set-env name=SCRAPER_COMMIT::$(git rev-parse HEAD)"
        
    - name: Scrape Data
      run: |
        # Don't fail if individual commands fail here. We'll manually fail
        # at the end.
        set +e +o pipefail
        # Temporary county-by-county outputs go in county_output/
        # Then we combine them at the end.
        echo "::set-env name=SCRAPER_TIME::$(date)"
        cd ${GITHUB_WORKSPACE}/scraper

        counties='alameda contra_costa marin napa san_francisco san_mateo santa_clara solano sonoma'
        mkdir county_output
        OUTPUT_FILE="${GITHUB_WORKSPACE}/site/data/data.v2.json"
        ERROR=''
        for county in $counties; do
          python scraper_data.py san_francisco > county_output/san_francisco.json
          if [ "${?}" -ne 0 ]; then ERROR=true; fi
        done

        # Merge all the new data on top of the old data and save.
        cp "${OUTPUT_FILE}" base.json
        jq -s 'reduce .[] as $county ({}; . + $county)' base.json county_output/*.json > "${OUTPUT_FILE}"

        # Exit with an error if any of the scrapers failed.
        if [ -n "${ERROR}" ]; then
          exit 1
        fi

    - name: Create PR if New Data
      uses: peter-evans/create-pull-request@v2
      with:
        path: site
        # If this branch already exists, it will be replaced with a commit
        # based on the changes from this job. If there's already a PR for it,
        # the PR will be updated. The end result is that each run of this job
        # supersedes or replaces any previous runs that haven't been reviewed
        # and merged yet.
        branch: auto-update-data
        title: 'GitHub action: data update'
        body: |
          Created using commit [${{env.SCRAPER_COMMIT}}](https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}})
          from sfbrigade/data-covid19-sfbayarea.
          
          Scraped at: ${{ env.SCRAPER_TIME }}
        commit-message: |
          GitHubAction: data update
          
          Created with commit ${{env.SCRAPER_COMMIT}} from sfbrigade/data-covid19-sfbayarea
          https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}}
        reviewers: Mr0grog
