name: Hello workflow
on:
  pull_request: {}
  workflow_call:
    inputs:
      name:
        required: false
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Say hello
        run: |
          echo 'HELLO, ${{ inputs.name || 'no-name' }}'
