name: Lint workflows
on: pull_request

permissions:
  actions: read,
  checks: write,
  contents: read,
  deployments: read,
  discussions: read,
  id-token: read,
  issues: read,
  metadata: read,
  packages: read,
  pages: read,
  pull-requests: read,
  repository-projects: read,
  security-events: read,
  statuses: write

jobs:
  lint_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml", ".github/workflows/*.yml"]'
