name: Lint workflows
# on: pull_request
on:
  pull_request:
    branches: [not-a-real-branch]

jobs:
  lint_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml", ".github/workflows/*.yml"]'
