name: Lint workflows
on: pull_request

jobs:
  lint_workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      deployments: read
      discussions: read
      id-token: none
      issues: read
      metadata: none
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: write
      whatever: read

    steps:
      - uses: actions/checkout@v2
      - name: Hello
        run: |
          echo "Hello"
      # - uses: cschleiden/actions-linter@v1
      #   with:
      #     workflows: '[".github/workflows/*.yaml", ".github/workflows/*.yml"]'
